// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_NlpvhtB3u5Za8bpkvw8c9jOXbdZQFOI',
    appId: '1:188246340948:android:945ed51694a94ba43bc4c1',
    messagingSenderId: '188246340948',
    projectId: 'richer-86cd4',
    storageBucket: 'richer-86cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0AHzrtKraz-YP6w14geL17-n-xfMV2E',
    appId: '1:188246340948:ios:1d2aae488d0b55b63bc4c1',
    messagingSenderId: '188246340948',
    projectId: 'richer-86cd4',
    storageBucket: 'richer-86cd4.firebasestorage.app',
    androidClientId: '188246340948-4c1utde7spl5veqpbkht6cootp90ups5.apps.googleusercontent.com',
    iosClientId: '188246340948-llen5n0bt2bmee4kmej0t1d8qsu0ot8b.apps.googleusercontent.com',
    iosBundleId: 'com.axiomtechdev.richtogether',
  );
}
